export const buttonStart = document.getElementById("btn-start")
export const buttonPrev = document.getElementById("btn-prev")
export const buttonNext = document.getElementById("btn-next")
export const buttonRandom = document.getElementById("btn-random")
export const searchInput = document.getElementById("search-input")
export const buttonSearch = document.getElementById("btn-search")
export const errorMsg = document.getElementById("error-msg")
export const mainContainer = document.getElementById("main-container")